###
POST http://localhost:8080/projects
Content-Type: application/json

{
  "projectName":"fdProject"
}

###
POST http://localhost:8080/projects/1/member
Content-Type: application/json

{
  "userId": "u2525424"
}

###
GET http://localhost:8080/projects/userName

###
GET http://localhost:8080/projects/project/1